"""add menu item reviews

Revision ID: 2ce16d185f9c
Revises: 6fd4417b0987
Create Date: 2026-09-25 14:23:13.139273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '2ce16d185f9c'
down_revision: Union[str, Sequence[str], None] = '6fd4417b0987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item_reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.item_id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.order_item_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_menu_item_reviews_customer_id'), 'menu_item_reviews', ['customer_id'], unique=False)
    op.create_index(op.f('ix_menu_item_reviews_item_id'), 'menu_item_reviews', ['item_id'], unique=False)
    op.create_index(op.f('ix_menu_item_reviews_order_item_id'), 'menu_item_reviews', ['order_item_id'], unique=True)
    op.create_table('menu_item_review_tags',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['menu_item_reviews.review_id'], ),
    sa.PrimaryKeyConstraint('review_id', 'tag')
    )
    op.create_index(op.f('ix_menu_item_review_tags_review_id'), 'menu_item_review_tags', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_menu_item_review_tags_review_id'), table_name='menu_item_review_tags')
    op.drop_table('menu_item_review_tags')
    op.drop_index(op.f('ix_menu_item_reviews_order_item_id'), table_name='menu_item_reviews')
    op.drop_index(op.f('ix_menu_item_reviews_item_id'), table_name='menu_item_reviews')
    op.drop_index(op.f('ix_menu_item_reviews_customer_id'), table_name='menu_item_reviews')
    op.drop_table('menu_item_reviews')
    # ### end Alembic commands ###
