"""add registration data to email verification

Revision ID: 6fd4417b0987
Revises: 995ba2e8de9b
Create Date: 2026-09-24 14:13:51.941775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '6fd4417b0987'
down_revision: Union[str, Sequence[str], None] = '995ba2e8de9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verifications', sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('email_verifications', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_verifications', 'password_hash')
    op.drop_column('email_verifications', 'user_name')
    # ### end Alembic commands ###
