"""add menu item image url

Revision ID: 82bcec5621c5
Revises: e1a66d0f972f
Create Date: 2026-09-15 14:32:13.978678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '82bcec5621c5'
down_revision: Union[str, Sequence[str], None] = 'e1a66d0f972f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'image_url')
    # ### end Alembic commands ###
