"""create offers tables

Revision ID: 954e867cbc2e
Revises: a20b7cdf0b68
Create Date: 2026-09-19 17:27:35.333003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '954e867cbc2e'
down_revision: Union[str, Sequence[str], None] = 'a20b7cdf0b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discount_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("discount_type IN ('PERCENTAGE', 'FIXED_PRICE')", name='ck_offers_type'),
    sa.CheckConstraint('discount_value > 0', name='ck_offers_value'),
    sa.CheckConstraint('end_at > start_at', name='ck_offers_window'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.shop_id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_index(op.f('ix_offers_end_at'), 'offers', ['end_at'], unique=False)
    op.create_index(op.f('ix_offers_shop_id'), 'offers', ['shop_id'], unique=False)
    op.create_table('offer_items',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.offer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id', 'item_id')
    )
    op.create_index(op.f('ix_offer_items_item_id'), 'offer_items', ['item_id'], unique=False)
  
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_items_item_id'), table_name='offer_items')
    op.drop_table('offer_items')
    op.drop_index(op.f('ix_offers_shop_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_end_at'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
