"""added quantity attribute incartitemoption

Revision ID: a20b7cdf0b68
Revises: b13f2419e75f
Create Date: 2026-09-18 17:45:33.929623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a20b7cdf0b68'
down_revision: Union[str, Sequence[str], None] = 'b13f2419e75f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_item_options', sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_item_options', 'quantity')
    # ### end Alembic commands ###
