"""add price mode to option groups

Revision ID: b13f2419e75f
Revises: f245659dda43
Create Date: 2026-09-18 09:44:39.564515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'b13f2419e75f'
down_revision: Union[str, Sequence[str], None] = 'f245659dda43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_item_option_groups', sa.Column('price_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_item_option_groups', 'price_mode')
    # ### end Alembic commands ###
