"""add offer snapshot to order items

Revision ID: c644726abfb4
Revises: 954e867cbc2e
Create Date: 2026-09-19 17:37:36.001716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'c644726abfb4'
down_revision: Union[str, Sequence[str], None] = '954e867cbc2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('original_unit_price', sa.Float(), nullable=True))
    op.add_column(
    'order_items',
    sa.Column(
        'discount_amount',
        sa.Float(),
        nullable=False,
        server_default='0'
    )
)   
    op.add_column('order_items', sa.Column('offer_id', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('offer_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(
    'fk_order_items_offer_id_offers',
    'order_items',
    'offers',
    ['offer_id'],
    ['offer_id'],
    ondelete='SET NULL'
)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
    'fk_order_items_offer_id_offers',
    'order_items',
    type_='foreignkey'
)    
    op.drop_column('order_items', 'offer_title')
    op.drop_column('order_items', 'offer_id')
    op.drop_column('order_items', 'discount_amount')
    op.drop_column('order_items', 'original_unit_price')
    
    # ### end Alembic commands ###
