"""add delivery partner and delivery models

Revision ID: d44317240f45
Revises: 233ce22eb58d
Create Date: 2026-10-07 17:50:47.303705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'd44317240f45'
down_revision: Union[str, Sequence[str], None] = '233ce22eb58d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###


    op.execute(
    "ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'delivery_partner'"
)
    op.create_table('delivery_partners',
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vehicle_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vehicle_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_VERIFICATION', 'APPROVED', 'ACTIVE', 'SUSPENDED', 'REJECTED', name='deliverypartnerstatus'), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('partner_id')
    )
    op.create_index(op.f('ix_delivery_partners_user_id'), 'delivery_partners', ['user_id'], unique=True)
    op.create_table('deliveries',
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_partner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_OFFER', 'OFFERED', 'ASSIGNED', 'ARRIVED_AT_SHOP', 'PICKED_UP', 'OUT_FOR_DELIVERY', 'ARRIVED_AT_CUSTOMER', 'DELIVERED', 'EXPIRED', 'CANCELLED', name='deliverystatus'), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('customer_fee', sa.Float(), nullable=True),
    sa.Column('partner_earning', sa.Float(), nullable=True),
    sa.Column('platform_fee', sa.Float(), nullable=True),
    sa.Column('offer_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offered_to_partner_ids', sa.JSON(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at_shop_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('out_for_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at_customer_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handover_otp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column(
    "handover_otp_attempts",
    sa.Integer(),
    nullable=False,
    ),
    sa.Column('handover_otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_partner_id'], ['delivery_partners.partner_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_index(op.f('ix_deliveries_delivery_partner_id'), 'deliveries', ['delivery_partner_id'], unique=False)
    op.create_index(op.f('ix_deliveries_order_id'), 'deliveries', ['order_id'], unique=True)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index(op.f('ix_deliveries_order_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_delivery_partner_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_delivery_partners_user_id'), table_name='delivery_partners')
    op.drop_table('delivery_partners')
    # ### end Alembic commands ###
