"""add kitchen staff

Revision ID: f1bae3af61ac
Revises: 0abb9f4357d6
Create Date: 2026-10-05 10:03:22.086212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'f1bae3af61ac'
down_revision: Union[str, Sequence[str], None] = '0abb9f4357d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitchen_staff',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('food_preference', sa.Enum('VEG', 'NON_VEG', name='foodpreference'), nullable=False),
    sa.Column('specialties', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_index(op.f('ix_kitchen_staff_user_id'), 'kitchen_staff', ['user_id'], unique=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_kitchen_staff_user_id'), table_name='kitchen_staff')
    op.drop_table('kitchen_staff')
    # ### end Alembic commands ###
