"""add due date

Revision ID: f6d785c297d3
Revises: d5ba81220f4c
Create Date: 2026-09-10 11:45:13.852501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6d785c297d3'
down_revision: Union[str, Sequence[str], None] = 'd5ba81220f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('shop_monthly_billings', sa.Column('due_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_monthly_billings', 'due_at')
    # ### end Alembic commands ###
